server:
  port: 8081
  contextPath: /uaa

bg:
  users:
    authorization:
      enabled: true
      clientId: bg-service
      clientSecret: bg-service
      scope: bg-service
      accessTokenValiditySeconds: 36000000
      refreshTokenValiditySeconds: 2592000

